# Generated by Django 5.1.4 on 2025-01-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainStatistics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("usd", models.DecimalField(decimal_places=4, max_digits=10)),
                ("eur", models.DecimalField(decimal_places=4, max_digits=10)),
                ("kzt", models.DecimalField(decimal_places=4, max_digits=10)),
                ("uah", models.DecimalField(decimal_places=4, max_digits=10)),
                ("byr", models.DecimalField(decimal_places=4, max_digits=10)),
                ("azn", models.DecimalField(decimal_places=4, max_digits=10)),
                ("uzs", models.DecimalField(decimal_places=4, max_digits=10)),
                ("kgs", models.DecimalField(decimal_places=4, max_digits=10)),
                ("gel", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
